---
- name: Upgrade Tomcat from 9.0.65 to 9.0.72
  hosts: all
  become: yes
  tasks:
    - name: Ensure the backup directory exists
      file:
        path: /tmp/tomcat_backup
        state: directory

    - name: Take backup of /conf directory
      copy:
        src: /opt/tomcat/apache-tomcat-9.0.65/conf/
        dest: /tmp/tomcat_backup/conf/
        remote_src: yes

    - name: Download Tomcat 9.0.72
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
        dest: /tmp/apache-tomcat-9.0.72.tar.gz

    - name: Extract Tomcat 9.0.72
      unarchive:
        src: /tmp/apache-tomcat-9.0.72.tar.gz
        dest: /opt/tomcat/
        remote_src: yes
        creates: /opt/tomcat/apache-tomcat-9.0.72

    - name: Stop current Tomcat service
      shell: /opt/tomcat/apache-tomcat-9.0.65/bin/shutdown.sh
      ignore_errors: yes

    - name: Copy configuration files from the backup to the new version
      copy:
        src: /tmp/tomcat_backup/conf/
        dest: /opt/tomcat/apache-tomcat-9.0.72/conf/
        remote_src: yes

    - name: Update symbolic link to point to the new Tomcat version
      file:
        src: /opt/tomcat/apache-tomcat-9.0.72
        dest: /opt/tomcat/latest
        state: link
        force: yes

    - name: Start the new Tomcat service
      shell: /opt/tomcat/apache-tomcat-9.0.72/bin/startup.sh

    - name: Clean up temporary files
      file:
        path: /tmp/apache-tomcat-9.0.72.tar.gz
        state: absent
